<!DOCTYPE html>
<html lang="id"><head><meta charset="utf-8"><title>{{ $po->po_number }} - Purchase Order</title>
<style>
@page{size:A4;margin:10mm}*{box-sizing:border-box}body{font-family:"Times New Roman",serif;color:#111;margin:0;font-size:12px}.page{min-height:277mm;padding:8mm 11mm;position:relative}.actions{position:fixed;right:18px;top:18px}.actions button{border:0;border-radius:6px;background:#3e568e;color:white;padding:9px 14px;cursor:pointer}.header{display:grid;grid-template-columns:1fr 1fr;align-items:start}.logo{max-width:240px;max-height:66px}.brand{font-family:Arial,sans-serif;font-weight:800;color:#16599a;font-size:25px}.title{font-size:21px;font-weight:700;color:#8194cc;margin-top:5px}.meta{margin-top:6px;width:100%;border-collapse:collapse}.meta td{padding:1px 4px}.meta td:last-child{background:#e6eaf3;text-align:center}.parties{display:grid;grid-template-columns:1fr 1fr;gap:70px;margin:32px 0 45px}.party-title{background:#405a92;color:#fff;font-weight:700;padding:2px 4px;width:75%;}.party-body{line-height:1.35;padding:2px 4px}.items{width:100%;border-collapse:collapse}.items th{background:#405a92;color:#fff;padding:3px;border:1px solid #222}.items td{border-left:1px solid #222;border-right:1px solid #222;border-bottom:1px solid #bbb;padding:3px}.items .last td{border-bottom:2px solid #111}.right{text-align:right}.center{text-align:center}.summary{width:35%;margin-left:auto;border-collapse:collapse}.summary td{padding:5px}.summary .total{border-top:2px solid #111;border-bottom:2px solid #111;font-weight:700}.instructions{margin-top:14px;border:1px solid #555;width:45%;min-height:75px}.instructions b{display:block;background:#c9c9c9;padding:2px}.instructions div{padding:5px;white-space:pre-line}.signature{margin:45px 0 0 auto;width:42%;text-align:center}.signature-space{height:65px}.signature-line{border-top:2px solid #111;font-weight:700;padding-top:4px}.footer{text-align:center;margin-top:25px;font-size:11px}@media print{.actions{display:none}.page{padding:0;min-height:auto}}
</style></head><body><div class="actions"><button onclick="window.print()">Cetak / Simpan PDF</button></div><div class="page">
<div class="header"><div>@if(!empty($settings['company_logo']))<img class="logo" src="{{ asset('storage/'.$settings['company_logo']) }}">@else<div class="brand">{{ strtoupper($settings['company_name'] ?? 'AULIACHEM PERKASA') }}</div>@endif</div><div><div class="title">PURCHASE ORDER (PO)</div><table class="meta"><tr><td><b>DATE:</b></td><td>{{ $po->order_date?->format('d/m/Y') }}</td></tr><tr><td><b>P.O.</b></td><td style="border:2px solid #111">{{ $po->po_number }}</td></tr></table></div></div>
<div class="parties"><div><div class="party-title">SUPPLIER</div><div class="party-body"><b>{{ $po->supplier?->supplier_name ?? '-' }}</b><br>{!! nl2br(e($po->supplier?->address ?? '-')) !!}</div></div><div><div class="party-title">DELIVERED TO</div><div class="party-body"><b>{{ strtoupper($settings['company_name'] ?? 'AULIACHEM PERKASA') }}</b><br>{!! nl2br(e($po->delivery_address ?: ($settings['company_address'] ?? 'Bratang Gede IV No. 8, Surabaya - Jawa Timur, Indonesia'))) !!}</div></div></div>
<table class="items"><thead><tr><th style="width:40px">NO</th><th>DESCRIPTION</th><th style="width:75px">UNIT</th><th style="width:90px">QTY</th><th style="width:130px">PRICE PER UNIT</th><th style="width:140px">TOTAL</th></tr></thead><tbody>
@foreach($po->items as $index=>$item)<tr><td class="center">{{ $index+1 }}</td><td>{{ $item->product_name }}@if($item->description)<br><small>{{ $item->description }}</small>@endif</td><td class="center">{{ $item->unit }}</td><td class="right">{{ number_format((float)$item->qty,3,',','.') }}</td><td class="right">{{ idr($item->buy_price) }}</td><td class="right">{{ idr($item->subtotal_cost) }}</td></tr>@endforeach
@for($i=$po->items->count();$i<12;$i++)<tr @class(['last'=>$i===11])><td>&nbsp;</td><td></td><td></td><td></td><td></td><td></td></tr>@endfor
</tbody></table><table class="summary"><tr><td>SUBTOTAL</td><td class="right">{{ idr($po->total_cost) }}</td></tr><tr class="total"><td>TOTAL</td><td class="right">{{ idr($po->total_cost) }}</td></tr></table>
<div class="instructions"><b>Special Instructions</b><div>{{ $po->special_instructions ?: ($po->notes ?: '-') }}</div></div>
<div class="signature"><div>Authorized by {{ $settings['company_name'] ?? 'Auliachem Perkasa' }}</div><div class="signature-space"></div><div class="signature-line">{{ $po->salesUser?->name ?? 'Authorized Signature' }}</div></div>
<div class="footer">Jika ada pertanyaan mengenai purchase order ini, silakan hubungi {{ $settings['company_phone'] ?? 'kantor kami' }}.</div>
</div></body></html>
